### ISSUE TITLE
Running Feature Extraction Missing Files

### ISSUE THREAD

**Issue by dylan6thomas** [UcarLab/CoRE-ATAC#1]
When running feature extraction according to the directions, the program returns:
`cat: atac_pbmc_500_v1_possorted_chr21_insertmetrics.txt: No such file or directory
rm: cannot remove 'atac_pbmc_500_v1_possorted_chr21_insertmetrics.txt': No such file or directory
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.NullPointerException
        at org.jax.peastools.insertmetrics.PeakInsertMetrics.getInsertMetrics(PeakInsertMetrics.java:72)
        at org.jax.peastools.insertmetrics.PeakInsertMetrics.main(PeakInsertMetrics.java:36)
        at org.jax.peastools.Main.main(Main.java:39)
        ... 5 more`

Then when running prediction, the program returns:
`FileNotFoundError: [Errno 2] No such file or directory: '/data/home/dylan.thomas/CoRE-ATAC/Data/core-atac-out/peak_features/atac_pbmc_500_v1_possorted_sequencefreq.txt'`
It seems I am missing files that would be created with feature extraction.
I am running the program in a shared server, so I did not have access to sudo rights. This meant I could not enter the sandbox directory using --writable. I'm not sure if that is what caused the problem.

**Comment by ajt986** [comment]
After reviewing these error messages, the problem is occurring with this line of code:

`		int npi = Math.min(1,peaks.length-1);`
where peaks is defined as:
`		Location[] peaks = util.getSortedLocationsWithIds(peakfile, chr);`

It looks like there are no peaks available for chr21 since all this is doing is grabbing the set of peaks for a specific chromosome. I would check the peak file and see if there are peaks for chr21. If there are no peaks for chr21, I would provide a different chromosome file that only includes chromosomes that exist in the peak file.

Let me know if this solves the issue.

Best,
Asa

**Comment by dylan6thomas** [comment]
It seems the problem was in my chromosome file, I had mistakenly forgotten to list the absolute directory. The missing files seem to be there. The extraction is running, so I will let you know when it is finished. Thank you!

Best,
Dylan
